name: Release Workflow

on:
  push:
    branches:
      - main  # adjust the branch if needed
  workflow_dispatch:
    

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # specify the Node.js version you want to install

    - name: Setup Go (Golang)
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'  # specify the Go version you want to install

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        # gcc
        sudo apt install gcc libc6-dev

        # x11
        sudo apt install libx11-dev xorg-dev libxtst-dev

        # Clipboard
        sudo apt install xsel xclip

        # Bitmap
        sudo apt install libpng++-dev

        # GoHook
        sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

    - name: Run release.js script
      run: node scripts/release.js
